<?php
require_once __DIR__ . '/includes/bootstrap.php';
require_once __DIR__ . '/config/db.php';
$pageTitle = 'Find trusted tutors in Bangladesh';
$subjects = [['name'=>'Mathematics','icon'=>'⌗'],['name'=>'Physics','icon'=>'⚛'],['name'=>'English','icon'=>'A'],['name'=>'Bangla','icon'=>'অ'],['name'=>'ICT','icon'=>'⌘'],['name'=>'Admission Coaching','icon'=>'✦']];
$tutors = [['name'=>'Nusrat Jahan','subject'=>'Mathematics','rating'=>'4.9','rate'=>'800','image'=>'https://images.unsplash.com/photo-1551836022-d5d88e9218df?auto=format&fit=crop&w=600&q=80'],['name'=>'Arif Rahman','subject'=>'Physics & ICT','rating'=>'4.8','rate'=>'700','image'=>'https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&w=600&q=80'],['name'=>'Tania Islam','subject'=>'English','rating'=>'5.0','rate'=>'650','image'=>'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=600&q=80']];
try { $dbSubjects = db()->query('SELECT name, icon FROM subjects ORDER BY id LIMIT 6')->fetchAll(); if ($dbSubjects) $subjects = $dbSubjects; $dbTutors = db()->query("SELECT u.full_name AS name, t.rating, t.hourly_rate AS rate, u.profile_picture AS image FROM tutors t JOIN users u ON u.id=t.user_id WHERE u.role = 'tutor' AND u.is_verified = 1 AND u.is_suspended = 0 AND t.is_featured=1 ORDER BY t.rating DESC LIMIT 3")->fetchAll(); if ($dbTutors) $tutors = $dbTutors; } catch (Throwable $e) { /* UI stays available before schema import. */ }
require __DIR__ . '/includes/header.php'; require __DIR__ . '/includes/navbar.php'; ?>
<main>
<section class="hero py-5 py-lg-0"><div class="container"><div class="row align-items-center min-vh-75 py-5"><div class="col-lg-6 py-lg-5"><p class="eyebrow mb-3">Learn with confidence</p><h1>Find the perfect tutor <span class="text-success">near you.</span></h1><p class="lead text-secondary my-4">Connect with skilled, trusted tutors for school, college, admission and more — anywhere in Bangladesh.</p><form class="search-box p-3 row g-2" action="#find-tutor"><div class="col-md-5"><select class="form-select" aria-label="Subject"><option>Choose a subject</option><option>Mathematics</option><option>English</option><option>Admission Coaching</option></select></div><div class="col-md-4"><select class="form-select" aria-label="Location"><option>Your area</option><option>Dhaka</option><option>Chattogram</option><option>Online</option></select></div><div class="col-md-3 d-grid"><button class="btn btn-brand">Search</button></div></form><div class="d-flex gap-4 mt-4 small text-secondary"><span>✓ Verified tutors</span><span>✓ Simple booking</span></div></div><div class="col-lg-6"><div class="hero-art"><div class="float-card one">⭐ 4.9 average tutor rating</div><img class="hero-photo" src="https://images.unsplash.com/photo-1523240795612-9a054b0db644?auto=format&fit=crop&w=900&q=85" alt="Students learning together"><div class="float-card two">🎓 1,200+ tutors ready to help</div></div></div></div></div></section>
<section id="find-tutor" class="section-pad"><div class="container"><div class="text-center mb-5"><p class="eyebrow">Start your search</p><h2 class="section-title">Find a tutor who fits your goals</h2></div><div class="p-4 p-lg-5 rounded-4 section-soft"><div class="row g-3"><div class="col-md-6 col-lg-3"><label class="form-label fw-semibold">Subject</label><select class="form-select"><option>All subjects</option><option>Math</option><option>Physics</option></select></div><div class="col-md-6 col-lg-3"><label class="form-label fw-semibold">Area</label><select class="form-select"><option>Anywhere in Bangladesh</option><option>Dhaka</option><option>Chattogram</option><option>Online</option></select></div><div class="col-md-6 col-lg-3"><label class="form-label fw-semibold">Level</label><select class="form-select"><option>Any level</option><option>School</option><option>College</option><option>University</option></select></div><div class="col-md-6 col-lg-3 d-grid align-self-end"><button class="btn btn-brand py-2">Find tutors</button></div></div></div></div></section>
<section class="section-pad section-soft"><div class="container"><div class="d-flex justify-content-between align-items-end mb-4"><div><p class="eyebrow mb-2">Popular subjects</p><h2 class="section-title mb-0">Learn what matters to you</h2></div><a class="text-success fw-semibold text-decoration-none" href="#find-tutor">View all →</a></div><div class="row g-3"><?php foreach ($subjects as $subject): ?><div class="col-6 col-md-4 col-lg-2"><a class="subject-card d-block" href="#find-tutor"><span class="subject-icon mb-3"><?= e($subject['icon'] ?: '◈') ?></span><strong><?= e($subject['name']) ?></strong><small class="d-block text-secondary mt-1">Find tutors</small></a></div><?php endforeach; ?></div></div></section>
<section class="section-pad"><div class="container"><div class="text-center mb-5"><p class="eyebrow">Meet our tutors</p><h2 class="section-title">Featured educators</h2></div><div class="row g-4"><?php foreach ($tutors as $tutor): ?><div class="col-md-6 col-lg-4"><article class="tutor-card"><img src="<?= e($tutor['image'] ?: 'https://images.unsplash.com/photo-1531123897727-8f129e1688ce?auto=format&fit=crop&w=600&q=80') ?>" alt="<?= e($tutor['name']) ?>"><div class="p-4"><div class="d-flex justify-content-between"><div><h5 class="mb-1"><?= e($tutor['name']) ?></h5><p class="text-secondary small mb-2"><?= e($tutor['subject'] ?? 'Experienced Tutor') ?></p></div><span class="rating">★ <?= e((string)$tutor['rating']) ?></span></div><div class="d-flex align-items-center justify-content-between border-top pt-3 mt-3"><span class="fw-bold">৳<?= e((string)$tutor['rate']) ?><small class="fw-normal text-secondary"> / hour</small></span><a href="#" class="btn btn-outline-brand btn-sm">View profile</a></div></div></article></div><?php endforeach; ?></div></div></section>
<section id="why-us" class="section-pad section-soft"><div class="container"><div class="text-center mb-5"><p class="eyebrow">Why TutorLagbe</p><h2 class="section-title">A better way to learn</h2></div><div class="row g-4"><?php foreach ([['✓','Verified Tutors','Every profile is reviewed so you can choose with confidence.'],['◷','Flexible scheduling','Learn online or in person at times that work for you.'],['৳','Affordable pricing','Compare rates and find value at every budget.'],['⌑','Secure payments','Simple, transparent payments for future bookings.']] as $feature): ?><div class="col-md-6 col-lg-3"><div class="feature-card"><div class="feature-icon mb-3"><?= $feature[0] ?></div><h5><?= $feature[1] ?></h5><p class="text-secondary mb-0 small"><?= $feature[2] ?></p></div></div><?php endforeach; ?></div></div></section>
<section class="section-pad"><div class="container"><div id="testimonials" class="carousel slide" data-bs-ride="carousel"><div class="carousel-inner text-center"><div class="carousel-item active"><div class="testimonial"><div class="quote-mark">“</div><blockquote class="fs-4 lh-base">TutorLagbe helped us find a wonderful math tutor for my daughter. Her confidence has changed completely.</blockquote><p class="mb-0 fw-bold">Farzana Ahmed</p><small class="text-secondary">Parent, Dhaka</small></div></div><div class="carousel-item"><div class="testimonial"><div class="quote-mark">“</div><blockquote class="fs-4 lh-base">I found an admission coach who understood exactly where I needed help. The process felt easy and safe.</blockquote><p class="mb-0 fw-bold">Rafiul Karim</p><small class="text-secondary">Student, Chattogram</small></div></div></div><div class="text-center mt-4"><button class="btn btn-outline-brand btn-sm me-2" data-bs-target="#testimonials" data-bs-slide="prev">←</button><button class="btn btn-outline-brand btn-sm" data-bs-target="#testimonials" data-bs-slide="next">→</button></div></div></div></section>
</main>
<?php require __DIR__ . '/includes/footer.php'; ?>
